import type { CardGameData } from './types'

export const initialCardGameData: CardGameData = {
  places: [
    { id: 'p1', name: 'Aldea del Este', description: 'Pequeña aldea junto al río.' },
    { id: 'p2', name: 'Torre del Mago', description: 'Torre encantada al norte del bosque.' },
  ],
  cards: [
    {
      id: 'c1',
      type: 'hero',
      name: 'Elena',
      relationship: 'Compañera de aventuras',
      hp: 120,
      strength: 14,
      agility: 18,
      intelligence: 16,
      class: 'Ladina',
      level: 5,
      sexualDescription: { genitals: 'Vagina.', bustSize: 'Mediano (C).' },
      physicalDescription: 'Elfa de pelo castaño, ojos verdes, complexión atlética.',
      race: 'Elfa',
      personality: 'Astuta, leal, algo sarcástica.',
      abilities: ['Esquiva', 'Sigilo', 'Cerraduras'],
    },
    {
      id: 'c-aria',
      type: 'hero',
      generalId: 'aria',
      name: 'Aria',
      relationship: 'General real, estratega del reino',
      hp: 100,
      strength: 10,
      agility: 12,
      intelligence: 18,
      class: 'Estratega',
      level: 6,
      sexualDescription: { genitals: 'Vagina.', bustSize: 'Mediano.' },
      physicalDescription: 'Alta y elegante, pelo rubio dorado en moño militar, ojos azules. Armadura real con emblema del reino.',
      race: 'Humana',
      personality: 'Líder nata, mente analítica, calmada bajo presión. Valora el honor y la justicia.',
      abilities: ['Estrategia de campo abierto', 'Espada real a dos manos', 'Táctica y liderazgo'],
    },
    {
      id: 'c-luna',
      type: 'hero',
      generalId: 'luna',
      name: 'Luna',
      relationship: 'General de la guardia real, defensora',
      hp: 100,
      strength: 10,
      agility: 14,
      intelligence: 14,
      class: 'Guardia',
      level: 5,
      sexualDescription: { genitals: 'Vagina.', bustSize: 'Mediano (B).' },
      physicalDescription: 'Complexión atlética, pelo plateado como la luna, ojos grises. Armadura de guardia con escudo y ornamentos plateados.',
      race: 'Humana',
      personality: 'Protectora, paciente y meticulosa. Leal hasta la muerte con quienes confía.',
      abilities: ['Defensa de fortaleza', 'Escudo real y espada corta', 'Protección de objetivos'],
    },
    {
      id: 'c-sakura',
      type: 'hero',
      generalId: 'sakura',
      name: 'Sakura',
      relationship: 'General diplomática, maestra de negociaciones',
      hp: 100,
      strength: 8,
      agility: 16,
      intelligence: 18,
      class: 'Diplomática',
      level: 5,
      sexualDescription: { genitals: 'Vagina.', bustSize: 'Pequeño (A).' },
      physicalDescription: 'Delicada y elegante, pelo rosa suave como pétalos de cerezo, ojos miel. Ropa diplomática con armadura ligera y abanico ceremonial.',
      race: 'Humana',
      personality: 'Diplomática y carismática, lee a la gente con facilidad. Resuelve conflictos con palabras antes que con espadas.',
      abilities: ['Negociación y espionaje', 'Abanico de guerra y daga oculta', 'Guerra psicológica'],
    },
    {
      id: 'c2',
      type: 'magic',
      name: 'Bola de Fuego',
      description: 'Invoca una esfera de fuego que explota al impactar.',
      effect: 'Daño en área',
      cost: '15 PM',
    },
    {
      id: 'c3',
      type: 'item',
      name: 'Poción de Curación',
      description: 'Restaura 50 HP al beberla.',
    },
    {
      id: 'c4',
      type: 'soldier',
      name: 'Guardia de la Aldea',
      hp: 30,
      attack: 5,
      description: 'Soldado raso de la milicia.',
    },
  ],
}
